---
title: "Bipartite foodweb"
author: "chloe"
date: "6 mars 2019"
output: html_document
---

## Get data ready
```{r setup, include=FALSE}
library(tidyverse)
library(readxl)

data_raw <- read_excel("../data/dietdata2.0.xlsx", sheet = "Sheet1", trim_ws=TRUE, na="NA")

data <- data_raw %>% 
  select(site_code,class,family_cor,fish_sp,genus_cor,sp_cor,item_type,
         item_kingdom, item_phylum , item_class,item_ord_cor,item_fam_cor,
         item_cor,item_gen_cor, item_sp_cor,grp_raw, nb_sample,nb_guts ,    
         nb_item ,     item_freq ,   item_volper,item_massper, item_numper,
         mean_SL  ,    min_SL  ,max_SL, min_TL ,max_TL,time,source) 

data <- unique(data)

#Create variable spname and replace "sp" by NA
data$item_spname <- paste(data$item_gen_cor, data$item_sp_cor, " ") #new variable with sp name
data$item_spname <- trimws(data$item_spname, which="both") 
data$item_spname[data$item_spname=="NA NA"] <- NA
data$item_sp_cor[data$item_sp_cor=="sp"] <- NA

#Add broad group
grp_item <-read.csv("../grp_item.csv", sep=";") #export the csv, so i can modify the csv directly
grp_item <- grp_item[,c(3,6)]
names(grp_item)[1] <- "grp_new"
grp_item <- (unique(grp_item))

grp_item$item_cor <- as.character(grp_item$item_cor) #now both variables are character

data_replace <- dplyr::left_join(data, grp_item, by = "item_cor") %>% 
                rename(grp = grp_new)
data_replace$grp <- as.character(data_replace$grp)

#Here just remove rows under certain conditions, pretty straight forward
data_replace <- filter(data_replace,!is.na(item_type)) #Remove items for which the type is NA  
data_replace <-filter(data_replace,!is.na(item_cor) , item_kingdom %in% c("Animalia","Plantae"))  #Remove row for which item = Na and kingdom Animalia or Plantae
data_replace <- filter(data_replace %>% filter(!item_cor=="Gurry"))  #remove gurry items
data_replace <- filter(data_replace, !item_cor=="Animalia" & !item_cor=="Plantae") 
data_replace <-filter(data_replace, is.na(time) | time =="day") #don't keep samples at night

#Create data frame per site
haw <- data_replace %>% filter(site_code=="haw")
vir <- data_replace %>% filter(site_code=="vir")
mari <- data_replace %>% filter(site_code=="mari")
mad <- data_replace %>% filter(site_code=="mad")

```

## Foodweb Fish families x item Phylum

```{r echo=FALSE}
library(bipartite)
#First need to build an interaction matrix on fish families and phylum 
str(vir)
n <- unique(vir$item_phylum) #18 phylum + 1 NA
m <- unique(vir$family_cor) #213 fish species, 56 families

x <- with(vir, table(vir$item_phylum,vir$family_cor))

vir.matrix <- matrix(0,ncol=length(m),nrow=length(n),dimnames=list(n,m))

i1 <- as.matrix(expand.grid(rownames(x),colnames(x)))

vir.matrix[i1] <- x[i1]

vir.matrix.std = vir.matrix/colSums(vir.matrix) #Standardized matrix

#Colors function
#Get interactions and box colors
phylum.all <- as.data.frame(vir[c(3,9)])
phylum.unique <- unique(phylum.all)
colnames(phylum.unique) <- c("Taxon", "Phyla")
phylum <- as.data.frame(unique(phylum.unique$Phyla))
phyla <- as.data.frame(phylum[-7,])
colnames(phyla) <- "Phyla"
phyla2 <- as.data.frame(phyla[order(phyla$Phyla),])
colnames(phyla2) <- "Phyla"

colfunc4 <- colorRampPalette(c("mediumpurple4","mediumblue","skyblue","lightseagreen","gold","coral1","gray85","black"))
colfunc4(16) #get 18 colors betweens those given into colorRampPalette
plot(rep(1,16),col=(colfunc4(16)),pch=19,cex=2) #plot to see the colours

phyla2$colors <- colfunc4(16)

colorvector <- as.data.frame(merge(phyla2, phylum.unique, by = "Phyla"))
names(colorvector)[2] <- "colors"
box.colors <- as.character(phyla2$colors)
colorvec1 <- as.character(colorvector$colors)
head(colorvec1)
colfunc4

#Plot
plotweb(vir.matrix.std,method="normal", empty = TRUE, arrow="down",text.rot=90,
        col.low = box.colors, bor.col.interaction = FALSE,y.width.low=0.05,     y.width.high=0.03,
        labsize = 1.2, ybig = 1.2, low.spacing = NULL)
```


## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
